version: '3.7'

services:
  node:
    image: minaprotocol/mina-daemon-baked:1.1.5-a42bdee
    container_name: node
    ports:
      - "${PORT}:8305"
    env_file:
      - ./.env
    environment:
      - "CODA_PRIVKEY_PASS=${CODA_PRIVKEY_PASS}"
    volumes:
      - ./keys:/keys:ro
      # - ./.mina-config:/root/.mina-config/
    networks:
      - mina_network
    restart: always
    command: [
      "daemon",
      "--insecure-rest-server",
      "--file-log-level", 
      "Debug",
      "--log-level",
      "Info",
      "--peer-list-url",
      "https://storage.googleapis.com/mina-seed-lists/mainnet_seeds.txt",
      "--external-port",
      "8305",
      "--limited-graphql-port",
      "3095",
      "--open-limited-graphql-port",
      "--snark-worker-fee",
      "0.02",
      "--snark-worker-parallelism",
      "1",
      "--run-snark-worker",
      "${SNARK_WORKER_KEY}",
      "--block-producer-key",
      "/keys/${BLOCK_PRODUCER_KEY}"
    ]
  sidecar:
    image: minaprotocol/mina-bp-stats-sidecar
    container_name: sidecar
    volumes:
      - ./mina-sidecar-config.json:/etc/mina-sidecar.json:ro
    networks:
      - mina_network
    restart: always
  monitor:
    image: graystake/mina-monitor:1.1.0
    container_name: monitor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mina_network
    restart: always

networks:
  mina_network:
    driver: overlay
    name: 'mina_network'